Repository src-d/landing, pull requests merged in 2019-07, with the labels that each got.

#440 Remove old pages
  hugo/content/engine.md
  hugo/content/lookout.md
  hugo/data/projects.yml
  hugo/layouts/engine/single.html
  hugo/layouts/index.html
  hugo/layouts/lookout/single.html
  hugo/layouts/open-source/single.html
  hugo/layouts/partials/try-sourced.html
Labels: enhancement

#439 Different fixes for the Landing
  hugo/layouts/community/single.html
  hugo/layouts/partials/header.html
  hugo/layouts/resources/single.html
  src/js/services/api.js
Labels: bug, enhancement

#437 Fix typo in index
  hugo/layouts/index.html
Labels: bug
